version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: uet_thesis_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=localhost
      - POSTGRES_DB=ecdsa_signatures
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 